---
title: Simpleyyt
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
subtitle: Yitao's Blog
description: Too simple, sometimes naive.
author: Simpleyyt
language: zh-Hans
date_format: "%Y-%m-%d"
url: 
baseurl: 
permalink: "/:year/:month/:day/:title/"
paginate: 20
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
- Gemfile
- Gemfile.lock
- README_en.md
- vendor
excerpt_separator: "<!--more-->"
highlighter: rouge
highlight:
  line_number: true
markdown: kramdown
kramdown:
  input: GFM
feed:
  path: atom.xml
plugins:
- jemoji
- jekyll-sitemap
- jekyll-feed
favicon: "/assets/images/author.jpeg"
keywords: Jekyll, NexT, simpleyyt, yitao
rss: 
since: 2015
authoricon: heart
copyright: true
canonical: true
seo: false
index_with_subtitle: false
menu:
  home: "/"
  archives: "/archives/"
  tags: "/tags/"
menu_icons:
  enable: true
  home: home
  about: user
  categories: th
  schedule: calendar
  tags: tags
  archives: archive
  sitemap: sitemap
  commonweal: heartbeat
scheme: Muse
font:
  enable: true
  host: 
  global:
    external: true
    family: Lato
  headings:
    external: true
    family: 
  posts:
    external: true
    family: 
  logo:
    external: true
    family: 
    size: 
  codes:
    external: true
    family: 
    size: 
social:
  GitHub: https://github.com/simpleyyt
  知乎: http://www.zhihu.com/people/yaoyit
social_icons:
  enable: true
  GitHub: github
  Twitter: twitter
  Weibo: weibo
avatar: "/assets/images/author.jpeg"
toc:
  enable: true
  number: true
  wrap: false
sidebar:
  position: left
  display: hide
  offset: 12
  offset_float: 0
  b2t: false
  scrollpercent: false
scroll_to_more: true
save_scroll: false
excerpt_description: true
auto_excerpt:
  enable: false
  length: 150
post_meta:
  item_text: true
  created_at: true
  updated_at: false
  categories: true
post_wordcount:
  item_text: true
  wordcount: false
  min2read: false
  separated_meta: true
post_copyright:
  enable: false
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/
custom_logo:
  enabled: false
  image: 
highlight_theme: normal
mathjax:
  enable: false
  per_page: false
  cdn: "//cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML"
han: false
baidu_analytics: 70b7e141dfc0ea2b204682f94ab2e01a
disqus:
  enable: true
  shortname: simpleyyt
  count: true
  hide: false
changyan:
  enable: false
  appid: 
  appkey: 
gitalk:
  enable: false
  clientID: 
  clientSecret: 
  repo: 
  owner: 
  admin: 
google_site_verification: hxyd6b4vb-uzYY6dVuzz4KXhScoVoEUjtiRWYSJVlrY
google_analytics: UA-67994495-1
duoshuo_info:
  ua_enable: true
  admin_enable: false
  user_id: 0
facebook_sdk:
  enable: false
  app_id: 
  fb_admin: 
  like_button: 
  webmaster: 
facebook_comments_plugin:
  enable: false
  num_of_posts: 10
  width: 100%
  scheme: light
vkontakte_api:
  enable: false
  app_id: 
  like: true
  comments: true
  num_of_posts: 10
rating:
  enable: false
  id: 
  color: fc6423
leancloud_visitors:
  enable: false
  app_id: 
  app_key: 
busuanzi_count:
  enable: false
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer: 
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer: 
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer: 
baidu_push: false
calendar:
  enable: false
  calendar_id: "<required>"
  api_key: "<required>"
  orderBy: startTime
  offsetMax: 24
  offsetMin: 4
  timeZone: 
  showDeleted: false
  singleEvents: true
  maxResults: 250
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: 'We didn''t find any results for the search: ${query}'
    hits_stats: "${hits} results found in ${time} ms"
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
exturl: false
use_motion: true
fancybox: true
pace: false
pace_theme: pace-theme-minimal
canvas_nest: false
three_waves: false
canvas_lines: false
canvas_sphere: false
canvas_ribbon: false
vendors:
  _internal: assets/lib
  jquery: 
  fancybox: 
  fancybox_css: 
  fastclick: 
  lazyload: 
  velocity: 
  velocity_ui: 
  ua_parser: 
  fontawesome: 
  algolia_instant_js: 
  algolia_instant_css: 
  pace: 
  pace_css: 
  canvas_nest: 
  three: 
  three_waves: 
  canvas_lines: 
  canvas_sphere: 
  canvas_ribbon: 
  han: 
css: assets/css
js: assets/js
images: assets/images
version: 5.1.1
